# escape=`

# Copy from https://github.com/cosmoconsult/github-runner-windows
ARG BASE
FROM mcr.microsoft.com/windows/servercore:2004
ENV VERSION 2.274.2

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
USER ContainerAdministrator
RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco install -y docker-cli; `
    choco install -y git ; `
    choco install -y jq; 

WORKDIR c:/actions-runner

# Install multiplatform powershell to be able use the pwsh shell for both ubuntu and self-hosted runnres
RUN Invoke-WebRequest -Uri \"https://github.com/actions/runner/releases/download/v$env:VERSION/actions-runner-win-x64-$env:VERSION.zip\" -OutFile actions-runner.zip -UseBasicParsing; `
    Expand-Archive actions-runner.zip -DestinationPath .; `
    Remove-Item actions-runner.zip; `
    Invoke-WebRequest -Uri  \"https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi\" -OutFile PowerShell-7.1.3-win-x64.msi -UseBasicParsing; `
    msiexec.exe /package PowerShell-7.1.3-win-x64.msi /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=0 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1

COPY cmd.ps1 .

CMD .\cmd.ps1