name: Jobs and artifacts

on:
  workflow_dispatch:

jobs:
  generate-artifact:
    runs-on: windows-latest
    outputs:
      ovalue: ${{ steps.with_output.outputs.ovalue }}  # map the step output to job output
    steps:
      # the id is necessary to be able reference the step
      # see also https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
      - name: Build
        id: with_output
        run: |
          mkdir -p artifacts
          echo 'ExampleValue' > artifacts/artifact.txt
          echo "::set-output name=ovalue::output value\n"
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-data
          path: artifacts/*.txt


  # You can only download artifacts in a workflow that were uploaded during the same workflow run.
  consume-artifact:
    runs-on: windows-latest
    needs: generate-artifact              # Defines dependency on the generate-artifact job
    steps:
      - name: Consume output
        run: |
          echo "${{ needs.generate-artifact.outputs.ovalue }}"
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-data
          path: ./downloaded
      - name: Display structure of downloaded files
        run: |
          Get-ChildItem ./downloaded
      - name: Consume
        run: |
          type downloaded/artifact.txt

  parallel-job:
    runs-on: ubuntu-latest
    needs: generate-artifact
    steps:
      - run: echo 'running other job'


  finishing-job:
    runs-on: windows-latest
    needs:  [consume-artifact, parallel-job]
    steps:
      - run: echo 'running finishing job'